Create extension
miraheze/ImportDump pull request #1
Opened 2022-04-18 05:46 UTC by Universal-Omega

2022-04-22 06:29 UTC, lens0021 requested changes

2022-04-22 06:32 UTC, Universal-Omega commented on includes/ImportDumpRequestManager.php
> +		// @phan-suppress-next-line PhanUndeclaredClassMethod
To avoid the dependencies for now. I guess it can be added to dependencies.

2022-04-22 06:33 UTC, Universal-Omega commented on composer.json
> +	"description": "",
Not having it resulted in the CI failing, so I just set it to an empty string.

2022-04-22 06:33 UTC, RhinosF1 commented on composer.json
> +	"description": "",
One should be given

2022-04-22 06:34 UTC, Universal-Omega commented on includes/SpecialRequestImportDump.php
> +			)->getConnectionRef( DB_PRIMARY, [], $this->getConfig()->get( 'ImportDumpCentralWiki' ) );
I'm not really sure how. I mean we could set a local variable assigning, but other than that the config is required to be passed those 3 times I think.

2022-04-22 06:34 UTC, RhinosF1 commented on includes/SpecialRequestImportDump.php
> +		}
It would make more sense surely to check if all 3 were equal

2022-04-22 06:35 UTC, Universal-Omega commented on includes/SpecialRequestImportDump.php
> +		}
So you can't simply reload and submit the request again by accident or on purpose. Though source can be allowed I guess.

2022-04-22 06:35 UTC, RhinosF1 commented on includes/ImportDumpRequestViewer.php
> +				],
That looks as expected to me

2022-04-22 06:36 UTC, Universal-Omega commented on includes/ImportDumpRequestManager.php
> +		}
Yeah it's a bit duplicate, but it's a different dbr being required so I guess we could assign both, and than row once, I'm not sure exactly how to better improve this though.

2022-04-22 06:36 UTC, RhinosF1 commented on includes/SpecialRequestImportDump.php
> +			)->getConnectionRef( DB_PRIMARY, [], $this->getConfig()->get( 'ImportDumpCentralWiki' ) );
Set a local variable.

2022-04-22 06:37 UTC, Universal-Omega commented on includes/ImportDumpRequestQueuePager.php
> +			'joins_conds' => [],
conds is used/assigned below this, on a if checked I believe.

2022-04-22 06:37 UTC, Universal-Omega commented on includes/ImportDumpRequestViewer.php
> +				Html::errorBox( wfMessage( 'importdump-unknown' )->escaped() )
Yes, its meant as privacy check.

2022-04-22 06:39 UTC, Universal-Omega commented on includes/ImportDumpRequestViewer.php
> +				],
Is info not escaped by default? Also there isn't user input here, so isn't XSS open either, not exactly sure what you mean? Mind clarifying?

2022-04-22 06:40 UTC, Universal-Omega commented on .gitignore
> +.github/*
Because originally when the CI was added for other extensions, it'd sometimes comment changes to .github, based off the things it pulls to there during the CI stages. I'm not sure if that is still required but I just left it.

2022-04-22 06:40 UTC, Universal-Omega commented on includes/SpecialRequestImportDump.php
> +			],
You are correct in your assumption for what it means, but yes it can probably be improved some, to give better wording. Thank you!

2022-04-22 06:42 UTC, Universal-Omega commented on includes/SpecialRequestImportDump.php
> +		}
This was one check that was just based off something in CreateWiki also, so that's why it is the way it is here.

2022-04-22 06:44 UTC, Universal-Omega commented on includes/SpecialRequestImportDump.php
> +		}
> It would make more sense surely to check if all 3 were equal

No, I wouldn't want to do that either. It opens the ability for spam, by simply changing one value. That's another major purpose of this check.

2022-04-22 06:44 UTC, RhinosF1 commented on includes/SpecialRequestImportDump.php
> +		}
Code shouldn't be copied simply because. There's got to be logic behind why the same set applies here. Commenting our code might help with that.

2022-04-22 06:44 UTC, Universal-Omega commented on extension.json
> +		"/*": "LogFormatter"
Correct, that's one of 2 things left to implement in this extension.

2022-04-22 06:45 UTC, Universal-Omega commented on composer.json
> +	"description": "",
I want to maintain this to be exactly like all our other extensions. If we do it here, we have to do it to all, I think, and I don't feel like doing that. So if you do, feel free, otherwise I think we can just leave it for now, and I can do it all later.

2022-04-22 06:46 UTC, RhinosF1 commented on includes/SpecialRequestImportDump.php
> +		}
> > It would make more sense surely to check if all 3 were equal
> 
> No, I wouldn't want to do that either. It opens the ability for spam, by simply changing one value. That's another major purpose of this check.

Anti-spam and Anti-Duplicate are 2 very different purposes for the same method. I'm not sure this is the best way of handling anti-spam. Maybe a rate limit?

2022-04-22 06:47 UTC, Universal-Omega commented on includes/ImportDumpRequestViewer.php
> +				],
Just to note, if the issue is no --username-prefix= value, it won't have one if it doesn't fine an interwiki prefix on the target wiki, or the central interwiki DB, so it'll just be empty in that case. Some sort of fallback like <unknown> could be added if we want to also.

2022-04-22 06:48 UTC, RhinosF1 commented on composer.json
> +	"description": "",
It's not exposed externally I don't think because we don't offer composer as a way to install our extensions, it's just for CI so it's very low on my list of things I care about but it should probably be considered one day.

2022-04-22 06:52 UTC, Universal-Omega commented on includes/SpecialRequestImportDump.php
> +		}
Rate limit still supported in this. I do want this check as an extra precaution to be extra safe. There's 2 reasons it's there, and also this one of the only things still in this extension directly from CreateWiki, the rest I redid to be more modern. If you want to add comments be my guest, it's more work, and if the code is clean enough, and easy enough for some to understand the reasoning, then I don't do comments, as its more work. There's reasons it may not be understood, which is why I'm explaining, but I really don't want to take the time to write inline comments for everything.

2022-04-22 06:52 UTC, lens0021 commented on includes/SpecialRequestImportDump.php
> +		}
Should it be

```php
$data['source'] == $row->request_source &&
$data['target'] == $row->request_target &&
$data['reason'] == $row->request_reason
```
instead of
```php
$data['source'] == $row->request_source ||
$data['target'] == $row->request_target ||
$data['reason'] == $row->request_reason
```
?

2022-04-22 06:54 UTC, lens0021 commented on .gitignore
> +.github/*
If the ignoring is not bothering you, then it is okay with me too.

2022-04-22 06:55 UTC, Universal-Omega commented on includes/SpecialRequestImportDump.php
> +		}
I don't want to do an && check, it should check various possibilities here. In fact, id almost rather just check reason here than do an and check. But either way, source should probably be removed, maybe even target, and just check comparisons on reason, and then we can implement rate limiting through `$wgRateLimits`.

2022-04-22 07:04 UTC, lens0021 commented on includes/ImportDumpRequestViewer.php
> +				],
What I wanted to mention is around the command, not the command itself. I think it would be good if it looks like this:

(Please ignore if the English is broken in the below example)

> If you submit this request, it will have the same effect on the execution of the next command on the server.:
> `php /var/www/html/maintenance/importDump.php --wiki=default --username-prefix=`
> See [the document](https://www.mediawiki.org/wiki/Manual:ImportDump.php) for details.

2022-04-22 07:19 UTC, Universal-Omega commented on includes/ImportDumpRequestViewer.php
> +				],
Your comments are always welcome and helpful and your thoughts will definitely be considered here. I will probably remove the "You are currently managing this request. This will update the status of this request." message entirely, and maybe add a label for the generated command here.

2022-04-22 07:26 UTC, lens0021 commented on includes/ImportDumpRequestViewer.php
> +				],
> What I wanted to mention is around the command, not the command itself. I think it would be good if it looks like this:
> 
> (Please ignore if the English is broken in the below example)
> 
> > If you submit this request, it will have the same effect on the execution of the next command on the server.:
> > `php /var/www/html/maintenance/importDump.php --wiki=default --username-prefix=`
> > See [the document](https://www.mediawiki.org/wiki/Manual:ImportDump.php) for details.

(*If you submit this request → If you set the status of this request to "Complete")

2022-04-24 17:13 UTC, Universal-Omega commented on includes/SpecialRequestImportDump.php
> +			],
Done. Thanks!

2022-04-24 17:14 UTC, Universal-Omega commented on includes/SpecialRequestImportDump.php
> +			)->getConnectionRef( DB_PRIMARY, [], $this->getConfig()->get( 'ImportDumpCentralWiki' ) );
Done. Thanks!

2022-06-08 03:17 UTC, merged