Rephrase "import dump"
miraheze/ImportDump pull request #69
Opened 2024-02-24 17:14 UTC by amire80

"ImportDump" is OK as an extension name,
but in messages, "import dump" is confusing.
Here, the word "dump" is removed from most
messages, and "import dump request" is changed
to simply "import request".

2024-02-26 23:23 UTC, Universal-Omega requested changes

2024-02-26 23:23 UTC, Universal-Omega commented on i18n/en.json
> +	"action-handle-import-dump-interwiki": "handle interwiki dump import",
This doesn't make sense to me. This isn't to handle an "interwiki dump" but rather to add interwiki prefixes to the remote wiki for --username-prefix,  but to me this makes it seem like we are importing an interwiki dump.

2024-02-26 23:23 UTC, Universal-Omega commented on i18n/en.json
> +	"right-handle-import-dump-interwiki": "Handle interwiki dump import",
Same thing here

2024-02-27 21:46 UTC, amire80 commented on i18n/en.json
> +	"action-handle-import-dump-interwiki": "handle interwiki dump import",
Oh, got it. How about "handle interwiki prefixes in dump imports"?

2024-02-27 21:52 UTC, Universal-Omega commented on i18n/en.json
> +	"action-handle-import-dump-interwiki": "handle interwiki dump import",
That's better, still a bit confusing, I was thinking maybe like "handle remote interwiki prefixes for import requests" or something (not exact and that may be to long also, overall I do agree with your wording changes here though.

2024-02-27 22:24 UTC, Universal-Omega approved these changes

2024-02-27 22:24 UTC, merged